Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC30A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC30A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC30A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC30A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC30A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC30A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC30A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC30A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A10
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A14
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A14
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A14
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A14
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC30A4
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC30A4
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC30A4
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC30A4
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC30A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC30A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC30A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC30A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC30A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC30A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC30A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC30A8
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC30A9
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC30A9
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC30A9
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC30A9
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A1
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A11
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A11
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A11
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A11
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A12
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A12
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A12
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A12
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A13
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A13
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A13
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A13
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A2
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A2
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A2
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A2
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A3
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A3
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A3
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A3
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A5
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A5
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A5
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A5
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A6
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A6
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A6
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A6
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A7
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A9
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A9
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A9
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A9