Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A13	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A13	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A13	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A13	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A2	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A2	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A2	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A2	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A3	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A3	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A3	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A3	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A5	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A5	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A5	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A5	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A6	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A6	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A6	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A6	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A7	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A7	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A7	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A7	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PMN	SLC39A9	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	Mo	SLC39A9	 
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	T	SLC39A9	
Rscript.exe --vanilla --verbose 	换做TCGA_LIHC的数据.R 	PI3K_AKT_mTOR	SLC39A9	